### ISSUE TITLE
`npm run test` is failing due to ngrxPush pipe not found

### ISSUE THREAD

**Issue by guillermoarellano** [stefanoslig/angular-ngrx-nx-realworld-example-app#32]
I forked and ran the application in an effort to learn more about using Cypress in a real world app using NX and NGRX. I am getting a couple of linting and Jest errors when running `npm run test` command. @stefanoslig Can you please help me?

```text
 PASS  apps/conduit/src/app/layout/footer/footer.component.spec.ts
 PASS  apps/conduit/src/app/layout/navbar/navbar.component.spec.ts
 FAIL  apps/conduit/src/app/app.component.spec.ts
  ● AppComponent › should create

    Template parse errors:
    The pipe 'ngrxPush' could not be found ("<conduit-navbar [isLoggedIn]="[ERROR ->]isLoggedIn$ | ngrxPush" [user]="user$ | ngrxPush"></conduit-navbar>
    "): ng:///DynamicTestModule/AppComponent.html@0:30
    The pipe 'ngrxPush' could not be found ("<conduit-navbar [isLoggedIn]="isLoggedIn$ | ngrxPush" [user]="[ERROR ->]user$ | ngrxPush"></conduit-navbar>
    <router-outlet></router-outlet>
    <conduit-footer></conduit-foote"): ng:///DynamicTestModule/AppComponent.html@0:62

      at syntaxError (../../../packages/compiler/src/util.ts:100:17)
      at TemplateParser.Object.<anonymous>.TemplateParser.parse (../../../packages/compiler/src/template_parser/template_parser.ts:106:13)
      at JitCompiler.Object.<anonymous>.JitCompiler._parseTemplate (../../../packages/compiler/src/jit/compiler.ts:297:33)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileTemplate (../../../packages/compiler/src/jit/compiler.ts:275:11)
      at ../../../packages/compiler/src/jit/compiler.ts:206:42
          at Set.forEach (<anonymous>)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileComponents (../../../packages/compiler/src/jit/compiler.ts:206:15)
      at ../../../packages/compiler/src/jit/compiler.ts:117:12
      at Object.then (../../../packages/compiler/src/util.ts:89:74)
```

**Comment by arrenv** [comment]
Hi @guillermoarellano,

I was able to fix this error by running the following in the console.

`npm i github:ngrx/component-builds
`

This link explains more on ngrxPush, which is in a new library that is not yet released - https://christiankohler.net/reactive-angular-with-ngrx-component

**Comment by guillermoarellano** [comment]
@arrenv -- I tried what you suggested. Below is what I tried doing fresh. 

- I grabbed a new fork of the project
- ran `npm i github:ngrx/component-builds`
- followed by `npm install`. 
- concluded with `npm run test`
- Result: I am still getting the same error. I think perhaps the versions of the packages being used are in conflict.

**Comment by stefanoslig** [comment]
Hi @guillermoarellano .I'll have a look tomorrow morning!
