### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by PavloPython** [stefanoslig/angular-ngrx-nx-realworld-example-app#71]
I have an issue while build the project
`$ ng serve --verbose

> nx run conduit:serve --verbose 
Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/home/projects/ser/angular-ngrx-nx-realworld-example-app/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:110:55)
    at ArchitectTargetJobRegistry._resolveBuilder (/home/projects/ser/angular-ngrx-nx-realworld-example-app/node_modules/@angular-devkit/architect/src/architect.js:101:54)
    at MergeMapSubscriber.project (/home/projects/ser/angular-ngrx-nx-realworld-example-app/node_modules/@angular-devkit/architect/src/architect.js:161:25)
    at MergeMapSubscriber._tryNext (/home/projects/ser/angular-ngrx-nx-realworld-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/home/projects/ser/angular-ngrx-nx-realworld-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/home/projects/ser/angular-ngrx-nx-realworld-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /home/projects/ser/angular-ngrx-nx-realworld-example-app/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24

———————————————————————————————————————————————

>  NX   ERROR  Running target "conduit:serve" failed

  Failed tasks:
  
  - conduit:serve
  
  Hint: run the command with --verbose for more details.

`

$ node -v
v16.10.0

**Comment by stefanoslig** [comment]
Hi @PavloPython ! I tried to reproduce this but it's not possible🤔
